name: Build and deploy .NET application to Container App silo

on:
  push:
    branches:
    - deploy

env:
  CONTAINER_APP_RESOURCE_GROUP_NAME: orleanssclr
  CONTAINER_REGISTRY_LOGIN_SERVER: orleanssclracr.azurecr.io

  SILO_DOCKER_FILE_PATH: Silo/Dockerfile
  SILO_IMAGE_NAME: silo

  DASHBOARD_DOCKER_FILE_PATH: Dashboard/Dockerfile
  DASHBOARD_IMAGE_NAME: dashboard

  MINIMAL_CLIENT_DOCKER_FILE_PATH: Clients.MinimalApi/Dockerfile
  MINIMAL_CLIENT_IMAGE_NAME: minimalapiclient

  WORKERSERVICE_CLIENT_DOCKER_FILE_PATH: Clients.WorkerService/Dockerfile
  WORKERSERVICE_CLIENT_IMAGE_NAME: workerserviceclient

  SCALER_DOCKER_FILE_PATH: Scaler/Dockerfile
  SCALER_IMAGE_NAME: scaler

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AzureSPN }}

    - name: Login to ACR
      run: |
        set -euo pipefail
        # see https://cloudarchitected.com/2021/09/logging-into-acr-in-github-actions/
        # see https://github.com/Azure/acr/blob/main/docs/AAD-OAuth.md#calling-post-oauth2exchange-to-get-an-acr-refresh-token
        access_token=$(az account get-access-token --query accessToken -o tsv)
        refresh_token=$(curl https://${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/oauth2/exchange -v -d "grant_type=access_token&service=${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}&access_token=$access_token" | jq -r .refresh_token)
        # The null GUID 0000... tells the container registry that this is an ACR refresh token during the login flow
        docker login -u 00000000-0000-0000-0000-000000000000 --password-stdin ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} <<< "$refresh_token"

    - name: Build and push Silo image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.SILO_IMAGE_NAME }}:${{ github.sha }}
        file: ${{ env.SILO_DOCKER_FILE_PATH }}
    
    - name: Build and push Dashboard image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.DASHBOARD_IMAGE_NAME }}:${{ github.sha }}
        file: ${{ env.DASHBOARD_DOCKER_FILE_PATH }}

    - name: Build and push Minimal Client image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.MINIMAL_CLIENT_IMAGE_NAME }}:${{ github.sha }}
        file: ${{ env.MINIMAL_CLIENT_DOCKER_FILE_PATH }}

    - name: Build and push Worker Service Client image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.WORKERSERVICE_CLIENT_IMAGE_NAME }}:${{ github.sha }}
        file: ${{ env.WORKERSERVICE_CLIENT_DOCKER_FILE_PATH }}

    - name: Build and push Scaler image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.SCALER_IMAGE_NAME }}:${{ github.sha }}
        file: ${{ env.SCALER_DOCKER_FILE_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AzureSPN }}

    - name: Login to ACR
      run: |
        set -euo pipefail
        # see https://cloudarchitected.com/2021/09/logging-into-acr-in-github-actions/
        # see https://github.com/Azure/acr/blob/main/docs/AAD-OAuth.md#calling-post-oauth2exchange-to-get-an-acr-refresh-token
        access_token=$(az account get-access-token --query accessToken -o tsv)
        refresh_token=$(curl https://${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/oauth2/exchange -v -d "grant_type=access_token&service=${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}&access_token=$access_token" | jq -r .refresh_token)
        # The null GUID 0000... tells the container registry that this is an ACR refresh token during the login flow
        docker login -u 00000000-0000-0000-0000-000000000000 --password-stdin ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} <<< "$refresh_token"
      
    - name: Installing Container Apps extension
      uses: azure/CLI@v1
      with:
        inlineScript: >
          echo "Installing containerapp extension"

          az config set extension.use_dynamic_install=yes_without_prompt

          az extension add --name containerapp --yes

    - name: Deploy Silo
      uses: azure/CLI@v1
      with:
        inlineScript: >
          echo "Deploying Silo"
          
          az containerapp registry set -n silo -g ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --server ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}

          az containerapp update -n silo -g ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} -i ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.SILO_IMAGE_NAME }}:${{ github.sha }}

    - name: Deploy Dashboard
      uses: azure/CLI@v1
      with:
        inlineScript: >
          echo "Deploying Dashboard"
          
          az containerapp registry set -n dashboard -g ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --server ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}

          az containerapp update -n dashboard -g ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} -i ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.DASHBOARD_IMAGE_NAME }}:${{ github.sha }}

    - name: Deploy Minimal API Client
      uses: azure/CLI@v1
      with:
        inlineScript: >
          echo "Deploying Minimal API Client"
          
          az containerapp registry set -n minimalapiclient -g ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --server ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}

          az containerapp update -n minimalapiclient -g ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} -i ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.MINIMAL_CLIENT_IMAGE_NAME }}:${{ github.sha }}

    - name: Deploy Worker Service Client
      uses: azure/CLI@v1
      with:
        inlineScript: >
          echo "Deploying Worker Service Client"
          
          az containerapp registry set -n workerserviceclient -g ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --server ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}

          az containerapp update -n workerserviceclient -g ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} -i ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.WORKERSERVICE_CLIENT_IMAGE_NAME }}:${{ github.sha }}

    - name: Deploy Scaler
      uses: azure/CLI@v1
      with:
        inlineScript: >
          echo "Deploying Scaler"
          
          az containerapp registry set -n scaler -g ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --server ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}

          az containerapp update -n scaler -g ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} -i ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.SCALER_IMAGE_NAME }}:${{ github.sha }}

    - name: logout
      run: >
        az logout
